103# -*- coding: utf-8 -*-
"""2prueba1d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhCiU78y64pgZrbcFQRPjz2ijuFTFbMh
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import time

# ⏱️ Iniciar cronómetro
inicio = time.time()

# Parámetros físicos y numéricos
100
N = 100                      # Número de celdas espaciales
dx = 1.0 / N                 # Tamaño de celda
gamma = 1.4                  # Razón de calores específicos (aire)
dt = 0.001                   # Paso de tiempo

# Preguntar al usuario cuántos pasos desea
pasos = int(input("¿Cuántos pasos de tiempo deseas simular? (Ej: 100) "))


# Inicialización de vectores U = [ρ, ρu, E]

U = np.zeros((N, 3))  # Cada fila contiene [rho, momentum, energy]

# Condiciones iniciales tipo Sod
for i in range(N):
    if i < N // 2:
        rho = 1.0
        p = 1.0
        u = 0.0
    else:
        rho = 0.125
        p = 0.1
        u = 0.0

    E = p / (gamma - 1) + 0.5 * rho * u**2
    U[i, 0] = rho
    U[i, 1] = rho * u
    U[i, 2] = E

# Guardamos historia de la densidad para animar
historia_rho = [U[:, 0].copy()]


# Función para calcular el flujo F(U)

def calcular_flujo(U):
    rho = U[:, 0]
    mom = U[:, 1]
    E = U[:, 2]
    u = mom / rho
    p = (gamma - 1) * (E - 0.5 * rho * u**2)

    F = np.zeros_like(U)
    F[:, 0] = mom                     # flujo de masa
    F[:, 1] = mom * u + p            # flujo de momento
    F[:, 2] = u * (E + p)            # flujo de energía
    return F

# Evolución temporal (Lax-Friedrichs)

for _ in range(pasos):
    F = calcular_flujo(U)
    U_new = np.zeros_like(U)

    for i in range(1, N - 1):
        U_new[i] = 0.5 * (U[i + 1] + U[i - 1]) \
                 - dt / (2 * dx) * (F[i + 1] - F[i - 1])

    # Condiciones de frontera: fijas
    U_new[0] = U[0]
    U_new[-1] = U[-1]
    U = U_new
    historia_rho.append(U[:, 0].copy())  # Guardamos la densidad

# ⏱️ Finalizar cronómetro y mostrar duración
fin = time.time()
print(f"⏱️ Tiempo de ejecución (serial): {fin - inicio:.4f} segundos")

# Animación con matplotlib

fig, ax = plt.subplots()
line, = ax.plot(historia_rho[0], lw=2)
ax.set_ylim(0, 1.1)
ax.set_title("Evolución de la densidad ρ (Sod)")

def actualizar(frame):
    line.set_ydata(historia_rho[frame])
    ax.set_xlabel(f"Paso: {frame}")
    return line,

ani = animation.FuncAnimation(fig, actualizar, frames=len(historia_rho), interval=30)
plt.show()